// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAty1iw53f6TWZI09rWDIaRU3j0NIGcVw8',
    appId: '1:938440587247:android:a7bea67161cd67bb8c681a',
    messagingSenderId: '938440587247',
    projectId: 'drinkup-c0636',
    storageBucket: 'drinkup-c0636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21MC6ZfM4Vt_zRh6s-Ed52FpQnJ5mIXA',
    appId: '1:938440587247:ios:cf024ad4f3d415ab8c681a',
    messagingSenderId: '938440587247',
    projectId: 'drinkup-c0636',
    storageBucket: 'drinkup-c0636.firebasestorage.app',
    iosClientId: '938440587247-drr8v5h7augashn990cf5fb1d18ekl5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.drinkup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21MC6ZfM4Vt_zRh6s-Ed52FpQnJ5mIXA',
    appId: '1:938440587247:ios:cf024ad4f3d415ab8c681a',
    messagingSenderId: '938440587247',
    projectId: 'drinkup-c0636',
    storageBucket: 'drinkup-c0636.firebasestorage.app',
    iosClientId: '938440587247-drr8v5h7augashn990cf5fb1d18ekl5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.drinkup',
  );
}
